{% set name = "Flask-Silk" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80a21faf09fe257443a4fbbf8cd3f6c793c567c87ff784751a1c38d2e18b5fbe

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}
    - flask >=0.8

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_silk

about:
  home: https://github.com/sublee/flask-silk
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Adds silk icons to your Flask application or blueprint, or extension'
  dev_url: https://github.com/sublee/flask-silk

extra:
  recipe-maintainers:
    - isuruf
